xdescribe('On exception', function () {
  it('the test fails', function () {
    throw new Error('fire!');
  })
})
